version: '2'

services:
    client:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: node-client
        ports:
            - "8080:8080"
        env_file: .env
        environment:
            API_BASE_PATH_URL: http://localhost:5000/api/advice
