version: "2"

services:
    backend:
        build: 
            context: ./api
            dockerfile: Dockerfile
        container_name: advice-app-backend
        ports:
            - 5000:5000
        environment:
            REDIS_ADDRESS: redis:6379
        links: 
            - db
    db:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
    frontend:
        build: 
            context: ./app
            dockerfile: Dockerfile
        container_name: advice-app-frontend
        ports:
            - "8080:8080"
        environment:
            API_BASE_URL_PATH: http://advice-app-backend:5000/api/advice
            PORT: 8080
        links: 
            - backend