version: '2'

services:
    frontend:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: advice-app-frontend
        ports:
            - "8080:8080"
        environment:
            API_BASE_PATH_URL: http://localhost:5000/api/advice
