version: "2"

services:
    tests:
        build:
            context: .
            dockerfile: test.dockerfile
        container_name: unit-tests
        ports:
            - 5000:5000
        environment:
            REDIS_ADDRESS: redis:6379
        links:
            - db
    db:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
