version: "2"

services:
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: advice-app-backend
        ports:
            - 5000:5000
        environment:
            REDIS_ADDRESS: redis:6379
        links: 
            - db
        networks:
            advice-app-net:
                ipv4_address: 172.16.238.10
    db:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        networks:
            - advice-app-net

networks:
    advice-app-net:
       driver: bridge
       ipam:
            driver: default
            config:
            - subnet: 172.16.238.0/24
              gateway: 172.16.238.1
            - subnet: 2001:3984:3989::/64
              gateway: 2001:3984:3989::1